type Link {
	id: ID!
	description: String!
	url: String!
	postedBy: User
	votes: [Vote!]!
}

type Subscription {
	newLink: Link
	newVote: Vote
}

type Query {
	feed: [Link!]!
	link(id: ID!): Link
}

type Mutation {
	post(url: String!, description: String!): Link!
}
