type Link {
	id: ID!
	description: String!
	url: String!
	postedBy: User
}

type Subscription {
	newLink: Link
}

type Query {
	feed: [Link!]!
	link(id: ID!): Link
}

type Mutation {
	post(url: String!, description: String!): Link!
}
